import type { MainPlan } from '../../types';

export const mainPlans: MainPlan[] = [
    {
      id: "main-1",
      annualPrice: 0,
      annualTotal: 0,
      setupFeeAnnual: 0,
      isPopular: false,
      isCustom: false,
      isFree: true,
      translations: {
        en: {
          name: "Free Page",
          buttonText: "Start Free",
          setupFeeNote: "No domain or email included — subdomain only. 💡 Perfect for experiencing our quality and starting your digital presence instantly with zero financial risk.",
          features: [
            "One dedicated informational page",
            "Professional design with a single Hero Background image",
            "Basic Logo Placement",
            "Interactive contact form with message reception",
            "100% mobile-friendly design",
            "Fast loading speed and free basic protection",
            "Basic SEO-ready structure",
            "Free subdomain hosting (yourname.axonxcode.com)",
          ],
        },
        ar: {
          name: "الباقة المجانية",
          buttonText: "ابدأ مجاناً",
          setupFeeNote: "بدون دومين أو إيميل مخصص — رابط فرعي فقط. 💡 مثالية لتجربة جودة عملنا وبدء حضورك الرقمي فوراً دون أي مخاطرة مادية.",
          features: [
            "صفحة معلوماتية واحدة مخصصة",
            "تصميم احترافي مع صورة خلفية رئيسية واحدة (Hero Background)",
            "وضع الشعار الأساسي (Logo Placement)",
            "نموذج تواصل تفاعلي واستقبال الرسائل",
            "تصميم متوافق 100% مع شاشات الهواتف الذكية",
            "سرعة تحميل عالية وحماية أساسية مجانية",
            "بنية أولية مهيأة لمحركات البحث (Basic SEO)",
            "استضافة مجانية على رابط فرعي (yourname.axonxcode.com)",
          ],
        },
        nl: {
          name: "Gratis Pagina",
          buttonText: "Start Gratis",
          setupFeeNote: "Geen domein of e-mail inbegrepen — alleen subdomein. 💡 Ideaal om onze kwaliteit te ervaren en direct te starten met uw digitale aanwezigheid, zonder enig financieel risico.",
          features: [
            "Eén op maat gemaakte informatiepagina",
            "Professioneel design met één Hero-achtergrondafbeelding",
            "Basis Logo Plaatsing",
            "Interactief contactformulier met berichtontvangst",
            "100% mobielvriendelijk ontwerp",
            "Snelle laadtijd en gratis basisbeveiliging",
            "SEO-klare basisstructuur",
            "Gratis subdomein hosting (yourname.axonxcode.com)",
          ],
        },
      },
    },
    {
      id: "main-2",
      annualPrice: 1299,
      annualTotal: 0,
      setupFeeAnnual: 0,
      isPopular: true,
      isCustom: false,
      translations: {
        en: {
          name: "Business Pro",
          buttonText: "Start Project",
          setupFeeNote: "🎁 Launch gift: your first month completely free (hosting + email + VIP content management), so you start your project with zero extra running costs!",
          features: [
            "5 to 8 fully custom pages (no templates)",
            "Multi-language support (Dutch/English, with option to add another language)",
            "Ultra-fast performance",
            "High-level security with continuous updates",
            "Mobile-friendly design + SEO ready",
            "Direct, interactive contact form for your clients",
            "VIP Managed content service: included in the monthly maintenance plan, we handle any text or image update for you monthly without dashboard complexity",
            "Optional add-ons on request: dynamic CMS dashboard, external API integrations, or custom software features",
            "Built-in visitor analytics (Google Analytics), fully compliant with EU cookie privacy requirements",
            "Price excludes domain & hosting — requires the monthly maintenance & hosting subscription",
          ],
        },
        ar: {
          name: "باقة الأعمال",
          buttonText: "ابدأ مشروعك",
          setupFeeNote: "🎁 هدية الباقة: أول شهر مجاناً بالكامل من باقة (الاستضافة + الإيميل + إدارة المحتوى VIP)، لتبدأ مشروعك بدون أي مصاريف تشغيلية إضافية!",
          features: [
            "5 إلى 8 صفحات مخصصة بالكامل (بدون قوالب جاهزة)",
            "دعم لغات متعددة (هولندي / إنجليزي / مع إمكانية إضافة لغات أخرى)",
            "سرعة فائقة",
            "أمان عالي المستوى وتحديث مستمر",
            "تصميم متوافق مع الموبايل + مهيأ لمحركات البحث (SEO)",
            "نموذج تواصل مباشر وتفاعلي مع عملائك",
            "خدمة إدارة المحتوى (VIP Managed): ضمن باقة الصيانة الشهرية ننجز لك أي تعديل على النصوص أو الصور شهرياً دون الحاجة لتعقيدات لوحات التحكم",
            "إضافات اختيارية حسب الطلب: لوحة تحكم CMS ديناميكية، ربط أنظمة خارجية (API)، أو تطوير ميزات برمجية خاصة",
            "تحليلات زوار مدمجة (Google Analytics) مع الالتزام بمتطلبات خصوصية الكوكيز الأوروبية",
            "السعر لا يشمل الدومين والاستضافة — يتطلب الاشتراك في باقة الصيانة والاستضافة الشهرية",
          ],
        },
        nl: {
          name: "Business Pro",
          buttonText: "Project Starten",
          setupFeeNote: "🎁 Startcadeau: uw eerste maand volledig gratis (hosting + e-mail + VIP contentbeheer), zodat u zonder extra operationele kosten start!",
          features: [
            "5 tot 8 volledig maatwerk pagina's (geen templates)",
            "Meertalige ondersteuning (Nederlands/Engels, met optie voor een extra taal)",
            "Supersnelle prestaties",
            "Hoog beveiligingsniveau met continue updates",
            "Mobielvriendelijk design + SEO klaar",
            "Direct, interactief contactformulier voor uw klanten",
            "VIP Managed contentservice: inbegrepen in het maandelijkse onderhoudsplan, wij verwerken elke tekst- of afbeeldingswijziging maandelijks voor u zonder dashboard-complexiteit",
            "Optionele add-ons op aanvraag: dynamisch CMS-dashboard, koppelingen met externe API's, of maatwerk software functies",
            "Ingebouwde bezoekersanalyse (Google Analytics), volledig conform de Europese cookie-privacyregels",
            "Prijs is exclusief domein & hosting — vereist het maandelijkse onderhouds- en hostingabonnement",
          ],
        },
      },
    },
    {
      id: "main-3",
      annualPrice: 0,
      annualTotal: 0,
      setupFeeAnnual: 0,
      isPopular: false,
      isCustom: true,
      translations: {
        en: {
          name: "Custom Solutions",
          buttonText: "Contact Us",
          setupFeeNote: "",
          customPriceLabel: "Custom Price",
          features: [
            "Advanced e-commerce store development (Custom E-commerce)",
            "Fully custom web applications and systems (Web & SaaS Apps)",
            "Administrative and operational workflow automation",
            "Scalable software architecture built for future growth",
            "Advanced integration with external systems, payment gateways, and accounting software (API Integration)",
            "Enterprise-grade custom dashboards and data management",
            "Solving complex software problems and optimizing existing systems",
            "Custom, high-security databases tailored to project scale and needs",
            "High-priority technical and security support, defined per project",
          ],
        },
        ar: {
          name: "الحلول المتقدمة",
          buttonText: "تواصل معنا",
          setupFeeNote: "",
          customPriceLabel: "سعر مخصص",
          features: [
            "تطوير المتاجر الإلكترونية المتقدمة (Custom E-commerce)",
            "تطبيقات ويب وأنظمة مخصصة بالكامل (Web & SaaS Apps)",
            "أتمتة العمليات الإدارية والتشغيلية للشركات (Workflow Automation)",
            "هندسة معمارية برمجية قابلة للتوسع المستقبلي (Scalable Architecture)",
            "ربط متقدم مع الأنظمة الخارجية، بوابات الدفع، وبرمجيات المحاسبة (API Integration)",
            "لوحات تحكم وإدارة بيانات مخصصة بمستوى الشركات (Enterprise Dashboards)",
            "حل المشاكل البرمجية المعقدة وتحسين أداء الأنظمة الحالية",
            "قواعد بيانات مخصصة وعالية الأمان حسب حجم واحتياجات المشروع",
            "دعم فني وأمني ذو أولوية قصوى، يُحدَّد حسب طبيعة كل مشروع",
          ],
        },
        nl: {
          name: "Maatwerk Oplossingen",
          buttonText: "Neem Contact Op",
          setupFeeNote: "",
          customPriceLabel: "Prijs op Maat",
          features: [
            "Ontwikkeling van geavanceerde webshops (Custom E-commerce)",
            "Volledig maatwerk webapplicaties en systemen (Web & SaaS Apps)",
            "Automatisering van administratieve en operationele workflows",
            "Schaalbare software-architectuur voor toekomstige groei",
            "Geavanceerde koppelingen met externe systemen, betalingsgateways en boekhoudsoftware (API-integratie)",
            "Maatwerk dashboards en databeheer op ondernemingsniveau",
            "Oplossen van complexe softwareproblemen en optimaliseren van bestaande systemen",
            "Maatwerk, hoogbeveiligde databases afgestemd op schaal en behoeften van het project",
            "Technische en beveiligingsondersteuning met hoge prioriteit, per project bepaald",
          ],
        },
      },
    },
];
